before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bundle
  - bundle exec rspec
rvm:
  - 1.9
  - 2.0
  - 2.1
  - jruby-19mode
  - rbx-2.2.7
notifications:
  email:
    on_success: always
    on_failure: always
